# Generated by Django 2.0.7 on 2018-07-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('media', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CardPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CardPage'),
        ),
    ]
