# Generated by Django 2.1 on 2018-08-23 09:15

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(help_text='The main text body to display on the card')),
                ('media', models.URLField(help_text='The absolute url to the image for the card')),
            ],
        ),
        migrations.CreateModel(
            name='CardPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('body', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eg: Polictical 1, Human Rights', max_length=20)),
                ('block', models.CharField(help_text='Eg: North, Science, Main', max_length=20)),
                ('room', models.CharField(help_text='Eg: C1, Lund Theater', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Eg: China, Egypt, Cuba', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_of', models.CharField(max_length=50)),
                ('preamble', django.contrib.postgres.fields.jsonb.JSONField(help_text='The preamble of the resolution in json form')),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(help_text='The body of the resolution in json form')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Delegate')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eg: UCS, Habs, City', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='delegation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='delegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Delegation'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CardPage'),
        ),
    ]
